// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OMF.ReviewManagement.Domain.Repositories;

namespace OMF.ReviewManagement.Migrations
{
    [DbContext(typeof(OMFReviewDbContext))]
    [Migration("20190907175621_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OMF.ReviewManagement.Domain.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsManualReviewRequired");

                    b.Property<string>("ModeratorTrackingId")
                        .IsRequired();

                    b.Property<string>("OrderId")
                        .IsRequired();

                    b.Property<decimal>("Rating");

                    b.Property<string>("ResturentID");

                    b.Property<string>("ResturentName")
                        .IsRequired();

                    b.Property<string>("ReviewText")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<string>("UserName");

                    b.HasKey("ReviewId");

                    b.HasIndex("ReviewId", "OrderId")
                        .IsUnique();

                    b.ToTable("reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
