// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OMF.OrderManagement.Domain.Repositories;

namespace OMF.OrderManagement.Migrations
{
    [DbContext(typeof(OMFOrderDbContext))]
    partial class OMFOrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OMF.OrderManagement.Domain.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.Property<string>("Shippingaddress")
                        .IsRequired();

                    b.Property<string>("UserId");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("OMF.OrderManagement.Domain.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OrderDate")
                        .IsRequired();

                    b.Property<string>("Orderitem")
                        .IsRequired();

                    b.Property<string>("Orderstatus")
                        .IsRequired();

                    b.Property<int>("PaymentId");

                    b.Property<int>("RestaurentId");

                    b.Property<float>("TotalPrice");

                    b.HasKey("OrderId");

                    b.HasIndex("PaymentId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("OMF.OrderManagement.Domain.PaymentInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alis")
                        .IsRequired();

                    b.Property<string>("CardHolderName")
                        .IsRequired();

                    b.Property<string>("CardNumber")
                        .IsRequired();

                    b.Property<string>("Cardtype")
                        .IsRequired();

                    b.Property<int>("CustomerId");

                    b.Property<string>("Expiration")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("PaymentDeatils");
                });

            modelBuilder.Entity("OMF.OrderManagement.Domain.Order", b =>
                {
                    b.HasOne("OMF.OrderManagement.Domain.PaymentInfo")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OMF.OrderManagement.Domain.PaymentInfo", b =>
                {
                    b.HasOne("OMF.OrderManagement.Domain.Customer")
                        .WithOne()
                        .HasForeignKey("OMF.OrderManagement.Domain.PaymentInfo", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
